export const WK_GROUPS = [
  { id: "A", teams: [
    { name: "België", flag: "be", fifa_rank: 3 },
    { name: "Argentinië", flag: "ar", fifa_rank: 1 },
    { name: "Australië", flag: "au", fifa_rank: 23 },
    { name: "Marokko", flag: "ma", fifa_rank: 14 },
  ]},
  { id: "B", teams: [
    { name: "Frankrijk", flag: "fr", fifa_rank: 2 },
    { name: "Brazilië", flag: "br", fifa_rank: 5 },
    { name: "Mexico", flag: "mx", fifa_rank: 16 },
    { name: "Ecuador", flag: "ec", fifa_rank: 34 },
  ]},
  { id: "C", teams: [
    { name: "Engeland", flag: "gb-eng", fifa_rank: 4 },
    { name: "Portugal", flag: "pt", fifa_rank: 6 },
    { name: "Iran", flag: "ir", fifa_rank: 21 },
    { name: "Canada", flag: "ca", fifa_rank: 48 },
  ]},
  { id: "D", teams: [
    { name: "Spanje", flag: "es", fifa_rank: 7 },
    { name: "Duitsland", flag: "de", fifa_rank: 12 },
    { name: "Japan", flag: "jp", fifa_rank: 17 },
    { name: "Senegal", flag: "sn", fifa_rank: 20 },
  ]},
  { id: "E", teams: [
    { name: "Nederland", flag: "nl", fifa_rank: 8 },
    { name: "Uruguay", flag: "uy", fifa_rank: 18 },
    { name: "USA", flag: "us", fifa_rank: 11 },
    { name: "Polen", flag: "pl", fifa_rank: 26 },
  ]},
  { id: "F", teams: [
    { name: "Kroatië", flag: "hr", fifa_rank: 9 },
    { name: "Colombia", flag: "co", fifa_rank: 13 },
    { name: "Nigeria", flag: "ng", fifa_rank: 35 },
    { name: "Zuid-Korea", flag: "kr", fifa_rank: 22 },
  ]},
];

export const STADIUMS = [
  { name: "MetLife Stadium", city: "New York", country: "USA", capacity: "82.500", emoji: "🇺🇸" },
  { name: "AT&T Stadium", city: "Dallas", country: "USA", capacity: "80.000", emoji: "🇺🇸" },
  { name: "SoFi Stadium", city: "Los Angeles", country: "USA", capacity: "70.240", emoji: "🇺🇸" },
  { name: "Estadio Azteca", city: "Mexico City", country: "Mexico", capacity: "87.523", emoji: "🇲🇽" },
  { name: "Rogers Centre", city: "Toronto", country: "Canada", capacity: "45.000", emoji: "🇨🇦" },
  { name: "Arrowhead Stadium", city: "Kansas City", country: "USA", capacity: "76.416", emoji: "🇺🇸" },
];

export const NEWS_ARTICLES = [
  {
    slug: "belgie-wk2026-kwalificatie",
    title: "België geplaatst voor WK 2026 — Rode Duivels terug op het grote podium",
    excerpt: "Na een spannende kwalificatiecampagne heeft België zich officieel geplaatst voor het FIFA WK 2026 in de VS, Canada en Mexico.",
    category: "België",
    date: "2026-03-01",
    readTime: 4,
    image: "be",
  },
  {
    slug: "wk2026-groepen-loting",
    title: "WK 2026 groepsloting — Wie speelt tegen wie?",
    excerpt: "De loting voor het FIFA WK 2026 heeft de 12 poules bepaald. Moeilijke groep voor België, maar kansen op doorstoot zijn reëel.",
    category: "WK 2026",
    date: "2026-02-28",
    readTime: 6,
    image: "trophy",
  },
  {
    slug: "topfavorieten-wk2026",
    title: "De 5 topfavorieten voor de WK 2026 titel",
    excerpt: "Argentinië, Brazilië, Frankrijk, Engeland of een verrassing? Wij analyseren de favorieten voor de wereldtitel.",
    category: "Analyse",
    date: "2026-02-27",
    readTime: 8,
    image: "ar",
  },
  {
    slug: "tickets-wk2026-kopen",
    title: "Tickets WK 2026 kopen — Alles wat je moet weten",
    excerpt: "Hoe koop je tickets voor het WK 2026? Prijzen, verkoopronden, resale — complete gids voor Belgische supporters.",
    category: "Tickets",
    date: "2026-02-26",
    readTime: 5,
    image: "us",
  },
  {
    slug: "beste-wk-apps-2026",
    title: "De beste apps om WK 2026 te volgen",
    excerpt: "Van live scores tot statistieken en fantasy football — onze top 10 apps voor de ultieme WK-beleving.",
    category: "Tech",
    date: "2026-02-25",
    readTime: 3,
    image: "trophy",
  },
  {
    slug: "wk2026-steden-gids",
    title: "Reizen naar WK 2026? Complete steden-gids",
    excerpt: "New York, Los Angeles, Dallas, Mexico City... alles wat je moet weten als je het WK 2026 ter plaatse wil beleven.",
    category: "Reizen",
    date: "2026-02-24",
    readTime: 10,
    image: "us",
  },
];

export const MERCHANDISE = [
  {
    name: "België Officieel WK 2026 Thuisshirt",
    price: "€89.95",
    originalPrice: "€99.95",
    badge: "🔥 Bestseller",
    emoji: "🇧🇪",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=belgie+wk+2026+shirt",
    rating: 4.8,
    reviews: 234,
  },
  {
    name: "WK 2026 Voetbal Officieel",
    price: "€149.95",
    badge: "⭐ Official",
    emoji: "⚽",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=wk+2026+voetbal+officieel",
    rating: 4.9,
    reviews: 89,
  },
  {
    name: "Belgische Voetbal Supporterssjaal WK",
    price: "€19.95",
    badge: "🛒 Populair",
    emoji: "🧣",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=belgie+supporter+sjaal+wk",
    rating: 4.6,
    reviews: 412,
  },
  {
    name: "WK 2026 Vlaggen Set (32 landen)",
    price: "€34.95",
    badge: "🎉 Nieuw",
    emoji: "🚩",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=wk+2026+vlaggen+set",
    rating: 4.7,
    reviews: 156,
  },
  {
    name: "Argentinië WK 2026 Shirt Messi",
    price: "€84.95",
    originalPrice: "€94.95",
    badge: "👑 Kampioen",
    emoji: "🇦🇷",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=argentinie+wk+2026+shirt+messi",
    rating: 4.9,
    reviews: 678,
  },
  {
    name: "WK 2026 Fanpakket Complete Set",
    price: "€59.95",
    badge: "💎 Topwaarde",
    emoji: "🎁",
    affiliateUrl: "https://www.bol.com/nl/nl/s/?searchtext=wk+2026+fanpakket",
    rating: 4.5,
    reviews: 93,
  },
];

export const BETTING_PARTNERS = [
  {
    name: "Unibet",
    logo: "🎯",
    offer: "€25 gratis wedden + €10 gratis casino",
    odds: { belgie: "12/1", argentinie: "5/2", frankrijk: "3/1" },
    url: "https://www.unibet.be/registration",
    color: "#1e6b3c",
    highlight: "Beste odds",
    disclaimer: "18+ | Speel met mate | BeGambleAware",
  },
  {
    name: "Betway",
    logo: "⚡",
    offer: "100% bonus tot €30 op je eerste storting",
    odds: { belgie: "10/1", argentinie: "3/1", frankrijk: "7/2" },
    url: "https://www.betway.be",
    color: "#00a651",
    highlight: "Live betting",
    disclaimer: "18+ | Kansspelen | Speel verantwoord",
  },
  {
    name: "Circus.be",
    logo: "🎪",
    offer: "€20 gratis op sport + €5 gratis spins",
    odds: { belgie: "11/1", argentinie: "11/4", frankrijk: "10/3" },
    url: "https://www.circus.be",
    color: "#e31837",
    highlight: "Belgische licentie",
    disclaimer: "18+ | Circus.be is erkend en vergund | Speel verantwoord",
  },
];
